package tr.com.vbt.lexer;

public enum Phase {
	
	START,
	TOKENIZE,
	PARSE_TO_COMMANDS,
	PARSE_TO_SOURCE_TREE,
	CONVERT_COBOL_TREE_TO_JAVA_TREE,
	WRITE_JAVA_CODE,
	CONVERT_NATURAL_TREE_TO_JAVA_TREE,
	CONVERT_NATURAL_TREE_TO_JSP_TREE,
	WRITE_JSP_CODE,
}
