package tr.com.vbt.lexer;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.commons.beanutils.ConvertUtils;
import org.apache.log4j.Logger;


import tr.com.vbt.token.AbstractToken;
import tr.com.vbt.token.TokenTipi;
import tr.com.vbt.util.ConverterConfiguration;

//FIND IDGIDBS-TGECICI WITH REFERANS=REFNUM AND TAMAM_KOD=0 --> schema ismi eklenmeyecek.
//FIND LIMAN WITH L-LIMAN-KODU EQ #P-LIMAN-KODU --> schema ismi eklenecek
//FIND HAN-FATURA WITH FT-BITIS-DONEM-KLIM-FIRM-FATURA EQ  --> schema ismi eklenecek
public class SchemaNameManager {

	final static Logger logger = Logger.getLogger(SchemaNameManager.class);

	private static Map<String, String> schemaNameMap = new HashMap<>();
	
	private static Map<String, String> tableNames = new HashMap<>();

	public static void addSchemaName(List<AbstractToken> tokenListesi) {

		String realTableName, synonymName;
		loadSchemaMap();
		String fullName, schemaName = null;
		String[] seperatedNames;

		AbstractToken schemaToken = null;

		for (int i = 0; i < tokenListesi.size() - 2; i++) {
			schemaToken = tokenListesi.get(i);
	
			if(!schemaToken.getTip().equals(TokenTipi.Kelime)|| schemaToken.getDeger().toString().length()<2){  
				continue;
			}
			
			logger.debug("Token:"+schemaToken.getDeger());
			fullName = schemaToken.getDeger().toString();
			
			if(!fullName.contains("_")){
				continue;
			}
		
			// fullName = IDGIDBS-TGECICI
			seperatedNames = fullName.split("_");

			try {
				//if (Configuration.isSchemaName(seperatedNames[0])) { // Schema Varsa

				//} else 
				if (isTable(fullName)) {//// Schema Yoksa ve TAble ise
					schemaName = schemaNameMap.get(fullName);
					if(schemaName==null || schemaName.length()==0){
						schemaName="TPS";
					}
					schemaToken.setDeger(schemaName + "_" + schemaToken.getDeger());
					logger.debug("SchemaManager:"+schemaName+"  is added");
					logger.debug("");
				}
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			
		}

	}

	private static void loadSchemaMap() {
		
		schemaNameMap.put("KET_AIRLINE", "TPS");
		schemaNameMap.put("KET_DOMESTIC", "TPS");
		schemaNameMap.put("KET_FDB", "TPS");
		schemaNameMap.put("KET_FRT", "TPS");
		schemaNameMap.put("KET_MILES", "TPS");
		schemaNameMap.put("KET_MULTIFILE", "TPS");
		schemaNameMap.put("KET_NOTE", "TPS");
		schemaNameMap.put("KET_NOTE_ATPCO", "TPS");
		schemaNameMap.put("KET_NOTE_CODE", "TPS");
		schemaNameMap.put("KET_TAX", "TPS");
		schemaNameMap.put("KET_NOTE_TAX_EXC", "TPS");
		
		schemaNameMap.put("ANLASMA", "PER");
		schemaNameMap.put("DEVF01", "PER");
		schemaNameMap.put("DFRF01", "PER");
		schemaNameMap.put("ENFF01", "PER");
		schemaNameMap.put("ERP-HAR", "PER");
		schemaNameMap.put("ERP-ISGRB", "PER");
		schemaNameMap.put("ERP-OBJECT", "PER");
		schemaNameMap.put("ERP-UNITE", "PER");
		schemaNameMap.put("IZINFILE", "PER");
		schemaNameMap.put("KET-BSR", "PER");
		schemaNameMap.put("KREF03", "PER");
		schemaNameMap.put("KSSF01", "PER");
		schemaNameMap.put("LOGFILE", "PER");
		schemaNameMap.put("MUVF05S1", "PER");
		schemaNameMap.put("PC-CABINET", "PER");
		schemaNameMap.put("PERF15", "PER");
		schemaNameMap.put("PERF30", "PER");
		schemaNameMap.put("PERF31", "PER");
		schemaNameMap.put("PERF34", "PER");
		schemaNameMap.put("PERF43", "PER");
		schemaNameMap.put("PERF50", "PER");
		schemaNameMap.put("PERF61", "PER");
		schemaNameMap.put("PERF90", "PER");
		schemaNameMap.put("PILF01", "PER");
		schemaNameMap.put("STAF01", "PER");
		schemaNameMap.put("UCRF01", "PER");
		schemaNameMap.put("UCRF02", "PER");
		schemaNameMap.put("UCRF15", "PER");
		schemaNameMap.put("UCRF20", "PER");
		schemaNameMap.put("UCRSTJ03", "PER");
		schemaNameMap.put("UCUF01", "PER");
		
		schemaNameMap.put("CAT-SEVK","IKR");
		schemaNameMap.put("GDR-DEBITCREDIT","IKR");
		schemaNameMap.put("GDR-ROL-BILGISI","IKR");
		schemaNameMap.put("GZT-IRSALIYE","IKR");
		schemaNameMap.put("IKR-BOARDINGCARD","IKR");
		schemaNameMap.put("IKR-FRM-MALZEME","IKR");
		schemaNameMap.put("IKR-GAZETE-UCUS","IKR");
		schemaNameMap.put("IKR-MENU","IKR");
		schemaNameMap.put("IKR-YEMEK","IKR");
		schemaNameMap.put("IKR-YUKPLN","IKR");
		schemaNameMap.put("TAR-SEFOP","IKR");
		schemaNameMap.put("TAR-SEKTOR","IKR");
		schemaNameMap.put("THY-CAT","IKR");
		schemaNameMap.put("UHM-ACILIS2","IKR");
		
		schemaNameMap.put("CAT_SEVK","IKR");
		schemaNameMap.put("GDR_DEBITCREDIT","IKR");
		schemaNameMap.put("GDR_ROL_BILGISI","IKR");
		schemaNameMap.put("GZT_IRSALIYE","IKR");
		schemaNameMap.put("IKR_BOARDINGCARD","IKR");
		schemaNameMap.put("IKR_FRM_MALZEME","IKR");
		schemaNameMap.put("IKR_GAZETE_UCUS","IKR");
		schemaNameMap.put("IKR_MENU","IKR");
		schemaNameMap.put("IKR_YEMEK","IKR");
		schemaNameMap.put("IKR_YUKPLN","IKR");
		schemaNameMap.put("TAR_SEFOP","IKR");
		schemaNameMap.put("TAR_SEKTOR","IKR");
		schemaNameMap.put("THY_CAT","IKR");
		schemaNameMap.put("UHM_ACILIS2","IKR");
		
		
		schemaNameMap.put("UCRF42","UCL");
		schemaNameMap.put("UCRF50","UCL");
		schemaNameMap.put("UCRF53","UCL");
		schemaNameMap.put("UCR-ZOR93A","UCL");
		schemaNameMap.put("UCR_ZOR93A","UCL");
		schemaNameMap.put("ZORF01","UCL");
		schemaNameMap.put("HAN-MUHASEBE","UCL");
		schemaNameMap.put("HAN_MUHASEBE","UCL");
		schemaNameMap.put("HRCH01","UCL");
		schemaNameMap.put("KONF99","UCL");
		schemaNameMap.put("KREF06","UCL");
		schemaNameMap.put("MUVF01","UCL");
		schemaNameMap.put("MUVF11","UCL");
		schemaNameMap.put("MUVF20","UCL");
		schemaNameMap.put("PASF00","UCL");
		schemaNameMap.put("UCRF07","UCL");
		schemaNameMap.put("UCRF10","UCL");
		schemaNameMap.put("UCRF30","UCL");
		schemaNameMap.put("UCRF40","UCL");
		
		schemaNameMap.put("UHM_NOT_A6","TCT");
		schemaNameMap.put("TKS_UCT_CN","TCT");
		schemaNameMap.put("TKS_TRF_OLD_AU","TCT");
		schemaNameMap.put("TKS_TRF_OLD_AI","TCT");
		schemaNameMap.put("TKS_TRF_DM","TCT");
		schemaNameMap.put("TKS_TRF_DA","TCT");
		schemaNameMap.put("TKS_TRF_D6","TCT");
		schemaNameMap.put("TKS_TRF_D1","TCT");
		schemaNameMap.put("TKS_TRF_D0","TCT");
		schemaNameMap.put("TKS_TRF_CG","TCT");
		schemaNameMap.put("TKS_TRF_AP","TCT");
		schemaNameMap.put("TKS_TRF_AO","TCT");
		schemaNameMap.put("TKS_TRF_AK","TCT");
		schemaNameMap.put("TKS_TRACE_INSURANCE_AK","TCT");
		schemaNameMap.put("TKS_REZ_OLD_AP","TCT");
		schemaNameMap.put("TKS_REZ_DF","TCT");
		schemaNameMap.put("TKS_REZ_DC","TCT");
		schemaNameMap.put("TKS_REZ_CM","TCT");
		schemaNameMap.put("TKS_REZ_CF","TCT");
		schemaNameMap.put("TKS_REZ_B6","TCT");
		schemaNameMap.put("TKS_POS_COUNTRY_CG","TCT");
		schemaNameMap.put("TKS_PARAM","TCT");
		schemaNameMap.put("TKS_NOT_SB","TCT");
		schemaNameMap.put("TKS_INVOICE_CR","TCT");
		schemaNameMap.put("TKS_INVOICE_CP","TCT");
		schemaNameMap.put("TKS_HANTRF_D3","TCT");
		schemaNameMap.put("TKS_HANTRF","TCT");
		schemaNameMap.put("TKS_GUMRUK_A2","TCT");
		schemaNameMap.put("TKS_E_FATURA_LOG_B0","TCT");
		schemaNameMap.put("TKS_E_FATURA_B1","TCT");
		schemaNameMap.put("TKS_E_CUSTOMER","TCT");
		schemaNameMap.put("TKS_EXP_AO","TCT");
		schemaNameMap.put("TKS_EXC_FM","TCT");
		schemaNameMap.put("TKS_EXC_AM","TCT");
		schemaNameMap.put("TKS_DUYURU_AL","TCT");
		schemaNameMap.put("TKS_DOM_IST_AD","TCT");
		schemaNameMap.put("TKS_DOM_DD","TCT");
		schemaNameMap.put("TKS_DOM_CD","TCT");
		schemaNameMap.put("TKS_DOM_B8","TCT");
		schemaNameMap.put("TKS_DOM_B2","TCT");
		schemaNameMap.put("TKS_CUSTOMER_DE_B3","TCT");
		schemaNameMap.put("TKS_CUSTOMER_DE","TCT");
		schemaNameMap.put("TKS_CUSTOMER","TCT");
		schemaNameMap.put("TKS_CRA_DA","TCT");
		schemaNameMap.put("TKS_CRA_CK","TCT");
		schemaNameMap.put("TKS_CRA_CE","TCT");
		schemaNameMap.put("TKS_CODE_B3","TCT");
		schemaNameMap.put("TKS_AWB_GJ","TCT");
		schemaNameMap.put("TKS_AWB_G5","TCT");
		schemaNameMap.put("TKS_AWB_FM","TCT");
		schemaNameMap.put("TKS_AWB_BH","TCT");
		schemaNameMap.put("TKS_AMB_OLD_EG","TCT");
		schemaNameMap.put("TKS_AMB_OLD_CZ","TCT");
		schemaNameMap.put("TKS_AMB_OLD_AC","TCT");
		schemaNameMap.put("TKS_AMB_HWB_HE","TCT");
		schemaNameMap.put("TKS_AMB_HWB_GE","TCT");
		schemaNameMap.put("TKS_AMB_DB20_DV","TCT");
		schemaNameMap.put("TKS_AMB_DB20_D0","TCT");
		schemaNameMap.put("TKS_AMB_DB20_B4","TCT");
		schemaNameMap.put("TKS_AMB_DB20_AV","TCT");
		schemaNameMap.put("TKS_ACC3","TCT");
		schemaNameMap.put("TFK_TKSMIS_INTERFACE_AC","TCT");
		schemaNameMap.put("MSW_FILE2_AT","TCT");
		schemaNameMap.put("MIS_SEGMENT1_JG","TCT");
		schemaNameMap.put("MIS_SEGMENT1_IZ","TCT");
		schemaNameMap.put("MIS_SEGMENT1_H1","TCT");
		schemaNameMap.put("MIS_SEGMENT1_FO","TCT");
		schemaNameMap.put("MIS_SEGMENT1_DN","TCT");
		schemaNameMap.put("MIS_SEGMENT1_BR","TCT");
		schemaNameMap.put("MIS_SEGMENT1","TCT");
		schemaNameMap.put("FSS_F01_S4","TCT");
		schemaNameMap.put("EKP_SKTUCAK_BG","TCT");
		schemaNameMap.put("EKP_SKTUCAK_AD","TCT");
		schemaNameMap.put("UHM_NOT_AJ","TCT");
		schemaNameMap.put("UHM_NOT_A8","TCT");
		schemaNameMap.put("TKS_TRF_OLD_D6","TCT");
		schemaNameMap.put("TKS_TRF_OLD_CP","TCT");
		schemaNameMap.put("TKS_TRF_OLD_CG","TCT");
		schemaNameMap.put("TKS_TRF_BC","TCT");
		schemaNameMap.put("TKS_TRF_AU","TCT");
		schemaNameMap.put("TKS_TRF_AT","TCT");
		schemaNameMap.put("TKS_TRF_AM","TCT");
		schemaNameMap.put("TKS_TRF_AJ","TCT");
		schemaNameMap.put("TKS_TRF","TCT");
		schemaNameMap.put("TKS_TRACE_INSURANCE_AX","TCT");
		schemaNameMap.put("TKS_TRACE_INSURANCE_AV","TCT");
		schemaNameMap.put("TKS_REZ_OLD_CP","TCT");
		schemaNameMap.put("TKS_REZ_OLD_B4","TCT");
		schemaNameMap.put("TKS_REZ_DS","TCT");
		schemaNameMap.put("TKS_REZ_DQ","TCT");
		schemaNameMap.put("TKS_REZ_BX","TCT");
		schemaNameMap.put("TKS_REZ_AV","TCT");
		schemaNameMap.put("TKS_POS_COUNTRY_AS","TCT");
		schemaNameMap.put("TKS_POS_COUNTRY","TCT");
		schemaNameMap.put("TKS_NOT","TCT");
		schemaNameMap.put("TKS_MSW_OLD_20_BN","TCT");
		schemaNameMap.put("TKS_MSW_OLD_20","TCT");
		schemaNameMap.put("TKS_MSG_ICARGO","TCT");
		schemaNameMap.put("TKS_MSG_A8","TCT");
		schemaNameMap.put("TKS_MIP_AF","TCT");
		schemaNameMap.put("TKS_MAIL","TCT");
		schemaNameMap.put("TKS_IST_AN","TCT");
		schemaNameMap.put("TKS_INVOICE_DB","TCT");
		schemaNameMap.put("TKS_INVOICE_CQ","TCT");
		schemaNameMap.put("TKS_INVOICE_CA","TCT");
		schemaNameMap.put("TKS_HANDLING_B8","TCT");
		schemaNameMap.put("TKS_HANDLING","TCT");
		schemaNameMap.put("TKS_FATURA","TCT");
		schemaNameMap.put("TKS_EXC_BA","TCT");
		schemaNameMap.put("TKS_EXC_B7","TCT");
		schemaNameMap.put("TKS_EXC_B1","TCT");
		schemaNameMap.put("TKS_DOM_IST_AO","TCT");
		schemaNameMap.put("TKS_DOM_IST_A1","TCT");
		schemaNameMap.put("TKS_DOM_D4","TCT");
		schemaNameMap.put("TKS_DOM_B1","TCT");
		schemaNameMap.put("TKS_DOM","TCT");
		schemaNameMap.put("TKS_CUSTOMER_B4","TCT");
		schemaNameMap.put("TKS_CURRENCY_AI","TCT");
		schemaNameMap.put("TKS_CRA_CA","TCT");
		schemaNameMap.put("TKS_CRA_AY","TCT");
		schemaNameMap.put("TKS_CF_AS","TCT");
		schemaNameMap.put("TKS_C2K_AL","TCT");
		schemaNameMap.put("TKS_BLK_JO","TCT");
		schemaNameMap.put("TKS_AWB_FF","TCT");
		schemaNameMap.put("TKS_AWB_FC","TCT");
		schemaNameMap.put("TKS_AWB_CE","TCT");
		schemaNameMap.put("TKS_AWB_C0","TCT");
		schemaNameMap.put("TKS_APD_AE","TCT");
		schemaNameMap.put("TKS_AMB_OLD_FA","TCT");
		schemaNameMap.put("TKS_AMB_OLD_DJ","TCT");
		schemaNameMap.put("TKS_AMB_OLD_DB","TCT");
		schemaNameMap.put("TKS_AMB_OLD_DA","TCT");
		schemaNameMap.put("TKS_AMB_OLD_D0","TCT");
		schemaNameMap.put("TKS_AMB_OLD_AV","TCT");
		schemaNameMap.put("TKS_AMB_HWB_HG","TCT");
		schemaNameMap.put("TKS_AMB_HWB_FP","TCT");
		schemaNameMap.put("TKS_AMB_HWB_DQ","TCT");
		schemaNameMap.put("TKS_AMB_DB20_FE","TCT");
		schemaNameMap.put("TKS_AMB_DB20_FA","TCT");
		schemaNameMap.put("TKS_AMB_DB20_EW","TCT");
		schemaNameMap.put("TKS_AMB_DB20_DA","TCT");
		schemaNameMap.put("TKS_AMB_DB20_BM","TCT");
		schemaNameMap.put("TKS_AMB_DB20_BG","TCT");
		schemaNameMap.put("TKS_ACC3_LABEL","TCT");
		schemaNameMap.put("TFK_TKSMIS_INTERFACE_BQ","TCT");
		schemaNameMap.put("TAR_LIMUCAK","TCT");
		schemaNameMap.put("MIS_SEGMENT1_IO","TCT");
		schemaNameMap.put("FSS_F02_CI","TCT");
		schemaNameMap.put("FSS_F02_CC","TCT");
		schemaNameMap.put("EKP_TARDEG","TCT");
		schemaNameMap.put("EKP_SKTUCAK_BR","TCT");
		schemaNameMap.put("EKP_SKTUCAK_B0","TCT");
		schemaNameMap.put("UHM_NOT","TCT");
		schemaNameMap.put("TKS_UCT_DH","TCT");
		schemaNameMap.put("TKS_TRF_OLD_CK","TCT");
		schemaNameMap.put("TKS_TRF_OLD_CD","TCT");
		schemaNameMap.put("TKS_TRF_OLD_C6","TCT");
		schemaNameMap.put("TKS_TRF_OLD_B6","TCT");
		schemaNameMap.put("TKS_TRF_OLD_AQ","TCT");
		schemaNameMap.put("TKS_TRF_OLD_AP","TCT");
		schemaNameMap.put("TKS_TRF_OLD_AK","TCT");
		schemaNameMap.put("TKS_TRF_D4","TCT");
		schemaNameMap.put("TKS_TRF_D2","TCT");
		schemaNameMap.put("TKS_TRF_CE","TCT");
		schemaNameMap.put("TKS_TRF_AW","TCT");
		schemaNameMap.put("TKS_TRACE_INSURANCE_AD","TCT");
		schemaNameMap.put("TKS_REZ_OLD_DH","TCT");
		schemaNameMap.put("TKS_REZ_OLD_CF","TCT");
		schemaNameMap.put("TKS_REZ_DP","TCT");
		schemaNameMap.put("TKS_POS_COUNTRY_AK","TCT");
		schemaNameMap.put("TKS_PFM_AN","TCT");
		schemaNameMap.put("TKS_MUHASEBE_B0","TCT");
		schemaNameMap.put("TKS_MUHASEBE_AP","TCT");
		schemaNameMap.put("TKS_MSW_OLD_B7","TCT");
		schemaNameMap.put("TKS_MSG_A7","TCT");
		schemaNameMap.put("TKS_MSG_A2","TCT");
		schemaNameMap.put("TKS_INVOICE","TCT");
		schemaNameMap.put("TKS_HANTRF_CA","TCT");
		schemaNameMap.put("TKS_HANTRF_C5","TCT");
		schemaNameMap.put("TKS_HANDLING_B5","TCT");
		schemaNameMap.put("TKS_HANDLING_A9","TCT");
		schemaNameMap.put("TKS_E_FATURA","TCT");
		schemaNameMap.put("TKS_E_CUSTOMER_A6","TCT");
		schemaNameMap.put("TKS_EXC_AS","TCT");
		schemaNameMap.put("TKS_DOM_CU","TCT");
		schemaNameMap.put("TKS_DOM_CC","TCT");
		schemaNameMap.put("TKS_DOM_AJ","TCT");
		schemaNameMap.put("TKS_CUSTOMER_DE_BH","TCT");
		schemaNameMap.put("TKS_CUSTOMER_DE_AP","TCT");
		schemaNameMap.put("TKS_CRA_DM","TCT");
		schemaNameMap.put("TKS_CRA_DD","TCT");
		schemaNameMap.put("TKS_CRA","TCT");
		schemaNameMap.put("TKS_CODE_D0","TCT");
		schemaNameMap.put("TKS_CF_BG","TCT");
		schemaNameMap.put("TKS_CF_BB","TCT");
		schemaNameMap.put("TKS_C2K","TCT");
		schemaNameMap.put("TKS_BLK_HB","TCT");
		schemaNameMap.put("TKS_BLK_FA","TCT");
		schemaNameMap.put("TKS_BLK_D2","TCT");
		schemaNameMap.put("TKS_BLK_BC","TCT");
		schemaNameMap.put("TKS_AWB_BG","TCT");
		schemaNameMap.put("TKS_AMB_OLD_D9","TCT");
		schemaNameMap.put("TKS_AMB_OLD_BF","TCT");
		schemaNameMap.put("TKS_AMB_OLD_AM","TCT");
		schemaNameMap.put("TKS_AMB_HWB_HH","TCT");
		schemaNameMap.put("TKS_AMB_HWB_FG","TCT");
		schemaNameMap.put("TKS_AMB_DB20_DJ","TCT");
		schemaNameMap.put("TKS_AMB_DB20_DC","TCT");
		schemaNameMap.put("TKS_AMB_DB20_CZ","TCT");
		schemaNameMap.put("TKS_AMB_DB20_CQ","TCT");
		schemaNameMap.put("TKS_AMB_DB20_C4","TCT");
		schemaNameMap.put("TKS_AMB_DB20_C3","TCT");
		schemaNameMap.put("TKS_AMB_DB20_AG","TCT");
		schemaNameMap.put("MIS_SEGMENT1_HR","TCT");
		schemaNameMap.put("MIS_SEGMENT1_GL","TCT");
		schemaNameMap.put("MIS_SEGMENT1_BK","TCT");
		schemaNameMap.put("INSCFC1_F4","TCT");
		schemaNameMap.put("FSS_F02_CD","TCT");
		schemaNameMap.put("FSS_F02_B3","TCT");
		schemaNameMap.put("FSS_F02_A7","TCT");
		schemaNameMap.put("UHM_NOT_AC","TCT");
		schemaNameMap.put("TKS_UCT_C3","TCT");
		schemaNameMap.put("TKS_TRF_OLD_D3","TCT");
		schemaNameMap.put("TKS_TRF_OLD_AW","TCT");
		schemaNameMap.put("TKS_TRF_OLD_AR","TCT");
		schemaNameMap.put("TKS_TRF_OLD_AM","TCT");
		schemaNameMap.put("TKS_TRF_OLD_AL","TCT");
		schemaNameMap.put("TKS_TRF_OLD","TCT");
		schemaNameMap.put("TKS_TRF_CM","TCT");
		schemaNameMap.put("TKS_TRF_CD","TCT");
		schemaNameMap.put("TKS_TRF_C6","TCT");
		schemaNameMap.put("TKS_TRF_B6","TCT");
		schemaNameMap.put("TKS_TRF_AR","TCT");
		schemaNameMap.put("TKS_TRACE_INSURANCE_F5","TCT");
		schemaNameMap.put("TKS_REZ_OLD_DQ","TCT");
		schemaNameMap.put("TKS_REZ_OLD_DN","TCT");
		schemaNameMap.put("TKS_REZ_OLD","TCT");
		schemaNameMap.put("TKS_REZ_DN","TCT");
		schemaNameMap.put("TKS_REZ_CP","TCT");
		schemaNameMap.put("TKS_REZ_B5","TCT");
		schemaNameMap.put("TKS_REZ_B3","TCT");
		schemaNameMap.put("TKS_REZ","TCT");
		schemaNameMap.put("TKS_NOT_A8","TCT");
		schemaNameMap.put("TKS_MSW_OLD_BN","TCT");
		schemaNameMap.put("TKS_MSW_OLD_B2","TCT");
		schemaNameMap.put("TKS_MSW_OLD_20_B8","TCT");
		schemaNameMap.put("TKS_MSW_OLD_20_B7","TCT");
		schemaNameMap.put("TKS_MSW_OLD_20_B3","TCT");
		schemaNameMap.put("TKS_MSW_OLD_20_B2","TCT");
		schemaNameMap.put("TKS_MSG_ICARGO_OLD","TCT");
		schemaNameMap.put("TKS_INVOICE_DJ","TCT");
		schemaNameMap.put("TKS_INVOICE_DF","TCT");
		schemaNameMap.put("TKS_INVOICE_CJ","TCT");
		schemaNameMap.put("TKS_HANTRF_DS","TCT");
		schemaNameMap.put("TKS_HANDLING_AL","TCT");
		schemaNameMap.put("TKS_E_FATURA_LOG","TCT");
		schemaNameMap.put("TKS_E_FATURA_B2","TCT");
		schemaNameMap.put("TKS_EXP_B1","TCT");
		schemaNameMap.put("TKS_EXP","TCT");
		schemaNameMap.put("TKS_EXC_F4","TCT");
		schemaNameMap.put("TKS_EXC_AR","TCT");
		schemaNameMap.put("TKS_DUYURU","TCT");
		schemaNameMap.put("TKS_DOM_DG","TCT");
		schemaNameMap.put("TKS_DOM_CQ","TCT");
		schemaNameMap.put("TKS_DOM_CG","TCT");
		schemaNameMap.put("TKS_DOM_C5","TCT");
		schemaNameMap.put("TKS_DOM_BU","TCT");
		schemaNameMap.put("TKS_CURRENCY","TCT");
		schemaNameMap.put("TKS_CRD","TCT");
		schemaNameMap.put("TKS_CRA_AI","TCT");
		schemaNameMap.put("TKS_BLK_JU","TCT");
		schemaNameMap.put("TKS_AWB_EQ","TCT");
		schemaNameMap.put("TKS_APD_AG","TCT");
		schemaNameMap.put("TKS_APD_AD","TCT");
		schemaNameMap.put("TKS_AMB_OLD_ER","TCT");
		schemaNameMap.put("TKS_AMB_OLD_EH","TCT");
		schemaNameMap.put("TKS_AMB_OLD_EF","TCT");
		schemaNameMap.put("TKS_AMB_OLD_DE","TCT");
		schemaNameMap.put("TKS_AMB_OLD_CQ","TCT");
		schemaNameMap.put("TKS_AMB_OLD_B4","TCT");
		schemaNameMap.put("TKS_AMB_OLD_AP","TCT");
		schemaNameMap.put("TKS_AMB_HWB_H4","TCT");
		schemaNameMap.put("TKS_AMB_HWB_FC","TCT");
		schemaNameMap.put("TKS_AMB_DB20_F8","TCT");
		schemaNameMap.put("TKS_AMB_DB20_F3","TCT");
		schemaNameMap.put("TKS_AMB_DB20_ER","TCT");
		schemaNameMap.put("TKS_AMB_DB20_EG","TCT");
		schemaNameMap.put("TAR_LIMUCAK_AA","TCT");
		schemaNameMap.put("MSW_FILE2_A4","TCT");
		schemaNameMap.put("MIS_SEGMENT1_FZ","TCT");
		schemaNameMap.put("INSCFC1_D0","TCT");
		schemaNameMap.put("INSCFC1_CA","TCT");
		schemaNameMap.put("INSCFC1_C0","TCT");
		schemaNameMap.put("INSCF03_S3","TCT");
		schemaNameMap.put("FSS_F02_CH","TCT");
		schemaNameMap.put("FSS_F01_BK","TCT");
		schemaNameMap.put("EKP_SKTUCAK_AA","TCT");
		schemaNameMap.put("EKP_SKTUCAK","TCT");
		schemaNameMap.put("TKS_UCT_BB","TCT");
		schemaNameMap.put("TKS_TRF_OLD_D0","TCT");
		schemaNameMap.put("TKS_TRF_OLD_AO","TCT");
		schemaNameMap.put("TKS_TRF_DK","TCT");
		schemaNameMap.put("TKS_TRF_CJ","TCT");
		schemaNameMap.put("TKS_TRF_CF","TCT");
		schemaNameMap.put("TKS_TRF_AI","TCT");
		schemaNameMap.put("TKS_TRACE_INSURANCE_AW","TCT");
		schemaNameMap.put("TKS_REZ_OLD_IND_A1","TCT");
		schemaNameMap.put("TKS_REZ_OLD_CO","TCT");
		schemaNameMap.put("TKS_REZ_DR","TCT");
		schemaNameMap.put("TKS_REZ_DH","TCT");
		schemaNameMap.put("TKS_REZ_C6","TCT");
		schemaNameMap.put("TKS_REZ_B4","TCT");
		schemaNameMap.put("TKS_POS_COUNTRY_CQ","TCT");
		schemaNameMap.put("TKS_POS_COUNTRY_CL","TCT");
		schemaNameMap.put("TKS_MUHASEBE_B3","TCT");
		schemaNameMap.put("TKS_MUHASEBE","TCT");
		schemaNameMap.put("TKS_MSW_OLD_BV","TCT");
		schemaNameMap.put("TKS_MSW_OLD_B3","TCT");
		schemaNameMap.put("TKS_MSW_OLD_20_B9","TCT");
		schemaNameMap.put("TKS_MSW_OLD","TCT");
		schemaNameMap.put("TKS_MSG_AN","TCT");
		schemaNameMap.put("TKS_MSG","TCT");
		schemaNameMap.put("TKS_MIP_A5","TCT");
		schemaNameMap.put("TKS_LOG","TCT");
		schemaNameMap.put("TKS_KNTAKY","TCT");
		schemaNameMap.put("TKS_IST_BA","TCT");
		schemaNameMap.put("TKS_IST","TCT");
		schemaNameMap.put("TKS_HANTRF_DP","TCT");
		schemaNameMap.put("TKS_HANTRF_D7","TCT");
		schemaNameMap.put("TKS_HANTRF_AE","TCT");
		schemaNameMap.put("TKS_HANTRF_A5","TCT");
		schemaNameMap.put("TKS_GUMRUK","TCT");
		schemaNameMap.put("TKS_EXP_B3","TCT");
		schemaNameMap.put("TKS_EXP_AR","TCT");
		schemaNameMap.put("TKS_EXC_B5","TCT");
		schemaNameMap.put("TKS_EXC_B2","TCT");
		schemaNameMap.put("TKS_DOM_IST","TCT");
		schemaNameMap.put("TKS_DOM_CT","TCT");
		schemaNameMap.put("TKS_DOM_BW","TCT");
		schemaNameMap.put("TKS_CUSTOMER_DE_BA","TCT");
		schemaNameMap.put("TKS_CUSTOMER_BZ","TCT");
		schemaNameMap.put("TKS_CUSTOMER_BJ","TCT");
		schemaNameMap.put("TKS_CUSTOMER_BA","TCT");
		schemaNameMap.put("TKS_CUSTOMER_AO","TCT");
		schemaNameMap.put("TKS_C2K_S2","TCT");
		schemaNameMap.put("TKS_C2K_C3","TCT");
		schemaNameMap.put("TKS_AWB_F4","TCT");
		schemaNameMap.put("TKS_AWB","TCT");
		schemaNameMap.put("TKS_AMB_OLD_DV","TCT");
		schemaNameMap.put("TKS_AMB_OLD_BG","TCT");
		schemaNameMap.put("TKS_AMB_OLD","TCT");
		schemaNameMap.put("TKS_AMB_HWB_FW","TCT");
		schemaNameMap.put("TKS_AMB_DB20_DE","TCT");
		schemaNameMap.put("TKS_AMB_DB20_BH","TCT");
		schemaNameMap.put("TKS_AMB_DB20_BF","TCT");
		schemaNameMap.put("MSW_FILE2_AG","TCT");
		schemaNameMap.put("MSW_FILE2_A9","TCT");
		schemaNameMap.put("MSW_FILE2","TCT");
		schemaNameMap.put("MIS_SEGMENT1_HH","TCT");
		schemaNameMap.put("MIS_SEGMENT1_DK","TCT");
		schemaNameMap.put("MIS_SEGMENT1_D9","TCT");
		schemaNameMap.put("INSCFC1_AK","TCT");
		schemaNameMap.put("INSCF03","TCT");
		schemaNameMap.put("FSS_F02_B2","TCT");
		schemaNameMap.put("EKP_SKTUCAK_C0","TCT");
		schemaNameMap.put("UHM_NOT_AL","TCT");
		schemaNameMap.put("TKS_UCT_AM","TCT");
		schemaNameMap.put("TKS_UCT","TCT");
		schemaNameMap.put("TKS_TRF_OLD_DK","TCT");
		schemaNameMap.put("TKS_TRF_OLD_CE","TCT");
		schemaNameMap.put("TKS_TRF_OLD_CC","TCT");
		schemaNameMap.put("TKS_TRF_OLD_AJ","TCT");
		schemaNameMap.put("TKS_TRF_DD","TCT");
		schemaNameMap.put("TKS_TRF_AQ","TCT");
		schemaNameMap.put("TKS_TRF_AL","TCT");
		schemaNameMap.put("TKS_TRACE_INSURANCE_S2","TCT");
		schemaNameMap.put("TKS_TRACE_INSURANCE_S1","TCT");
		schemaNameMap.put("TKS_TRACE_INSURANCE_AL","TCT");
		schemaNameMap.put("TKS_REZ_OLD_DS","TCT");
		schemaNameMap.put("TKS_REZ_OLD_DF","TCT");
		schemaNameMap.put("TKS_REZ_OLD_DC","TCT");
		schemaNameMap.put("TKS_REZ_OLD_D0","TCT");
		schemaNameMap.put("TKS_REZ_OLD_CU","TCT");
		schemaNameMap.put("TKS_REZ_OLD_CB","TCT");
		schemaNameMap.put("TKS_REZ_OLD_B6","TCT");
		schemaNameMap.put("TKS_REZ_OLD_AV","TCT");
		schemaNameMap.put("TKS_REZ_ED","TCT");
		schemaNameMap.put("TKS_POS_COUNTRY_CE","TCT");
		schemaNameMap.put("TKS_PFM","TCT");
		schemaNameMap.put("TKS_NOT_A7","TCT");
		schemaNameMap.put("TKS_MSW_OLD_B8","TCT");
		schemaNameMap.put("TKS_MAIL_AY","TCT");
		schemaNameMap.put("TKS_LOG_A6","TCT");
		schemaNameMap.put("TKS_IST_AQ","TCT");
		schemaNameMap.put("TKS_INVOICE_CL","TCT");
		schemaNameMap.put("TKS_HANTRF_DC","TCT");
		schemaNameMap.put("TKS_E_FATURA_B0","TCT");
		schemaNameMap.put("TKS_EXC_FG","TCT");
		schemaNameMap.put("TKS_EXC_AU","TCT");
		schemaNameMap.put("TKS_EXC_AA","TCT");
		schemaNameMap.put("TKS_EXC","TCT");
		schemaNameMap.put("TKS_ERR","TCT");
		schemaNameMap.put("TKS_DOM_IST_AF","TCT");
		schemaNameMap.put("TKS_DOM_DB","TCT");
		schemaNameMap.put("TKS_DOM_DA","TCT");
		schemaNameMap.put("TKS_DOM_CB","TCT");
		schemaNameMap.put("TKS_DOM_CA","TCT");
		schemaNameMap.put("TKS_CUSTOMER_DE_BJ","TCT");
		schemaNameMap.put("TKS_CUSTOMER_DE_B4","TCT");
		schemaNameMap.put("TKS_CUSTOMER_DE_AT","TCT");
		schemaNameMap.put("TKS_CUSTOMER_BH","TCT");
		schemaNameMap.put("TKS_CUSTOMER_B3","TCT");
		schemaNameMap.put("TKS_CUSTOMER_AP","TCT");
		schemaNameMap.put("TKS_CRA_DN","TCT");
		schemaNameMap.put("TKS_CRA_B3","TCT");
		schemaNameMap.put("TKS_CRA_B2","TCT");
		schemaNameMap.put("TKS_CODE_AA","TCT");
		schemaNameMap.put("TKS_C2K_CM","TCT");
		schemaNameMap.put("TKS_BLK_JH","TCT");
		schemaNameMap.put("TKS_AWB_DD","TCT");
		schemaNameMap.put("TKS_AWB_CZ","TCT");
		schemaNameMap.put("TKS_AWB_BI","TCT");
		schemaNameMap.put("TKS_APD_AH","TCT");
		schemaNameMap.put("TKS_AMB_OLD_EW","TCT");
		schemaNameMap.put("TKS_AMB_OLD_EE","TCT");
		schemaNameMap.put("TKS_AMB_OLD_DC","TCT");
		schemaNameMap.put("TKS_AMB_OLD_CJ","TCT");
		schemaNameMap.put("TKS_AMB_OLD_C4","TCT");
		schemaNameMap.put("TKS_AMB_OLD_AG","TCT");
		schemaNameMap.put("TKS_AMB_HWB_FM","TCT");
		schemaNameMap.put("TKS_AMB_HWB_CJ","TCT");
		schemaNameMap.put("TKS_AMB_HWB","TCT");
		schemaNameMap.put("TKS_AMB_DB20_DD","TCT");
		schemaNameMap.put("TKS_AMB_DB20","TCT");
		schemaNameMap.put("TKS_ACT","TCT");
		schemaNameMap.put("TFK_TKSMIS_INTERFACE_A2","TCT");
		schemaNameMap.put("TFK_TKSMIS_INTERFACE","TCT");
		schemaNameMap.put("MSW_FILE2_AE","TCT");
		schemaNameMap.put("MSW_FILE2_A8","TCT");
		schemaNameMap.put("MIS_SEGMENT1_ID","TCT");
		schemaNameMap.put("MIS_SEGMENT1_F6","TCT");
		schemaNameMap.put("MIS_SEGMENT1_CF","TCT");
		schemaNameMap.put("FSS_F02","TCT");
		schemaNameMap.put("EKP_SKTUCAK_AV","TCT");
		schemaNameMap.put("EKP_SKTUCAK_AK","TCT");
		schemaNameMap.put("UHM_NOT_AA","TCT");
		schemaNameMap.put("TKS_TRF_OLD_D5","TCT");
		schemaNameMap.put("TKS_TRF_OLD_CM","TCT");
		schemaNameMap.put("TKS_TRF_OLD_CF","TCT");
		schemaNameMap.put("TKS_TRF_DL","TCT");
		schemaNameMap.put("TKS_TRF_D5","TCT");
		schemaNameMap.put("TKS_TRF_D3","TCT");
		schemaNameMap.put("TKS_TRF_CY","TCT");
		schemaNameMap.put("TKS_TRF_CS","TCT");
		schemaNameMap.put("TKS_TRF_CK","TCT");
		schemaNameMap.put("TKS_TRACE_INSURANCE_F4","TCT");
		schemaNameMap.put("TKS_SUNEXP_EMAIL","TCT");
		schemaNameMap.put("TKS_REZ_OLD_C6","TCT");
		schemaNameMap.put("TKS_REZ_OLD_BX","TCT");
		schemaNameMap.put("TKS_REZ_OLD_BQ","TCT");
		schemaNameMap.put("TKS_REZ_OLD_B5","TCT");
		schemaNameMap.put("TKS_REZ_OLD_B3","TCT");
		schemaNameMap.put("TKS_REZ_DO","TCT");
		schemaNameMap.put("TKS_REZ_D0","TCT");
		schemaNameMap.put("TKS_REZ_CU","TCT");
		schemaNameMap.put("TKS_REZ_CO","TCT");
		schemaNameMap.put("TKS_REZ_CB","TCT");
		schemaNameMap.put("TKS_POS_COUNTRY_AX","TCT");
		schemaNameMap.put("TKS_NOT_A6","TCT");
		schemaNameMap.put("TKS_MSW_OLD_B9","TCT");
		schemaNameMap.put("TKS_MSW_OLD_20_BV","TCT");
		schemaNameMap.put("TKS_MIP","TCT");
		schemaNameMap.put("TKS_MAIL_AM","TCT");
		schemaNameMap.put("TKS_LOG_B0","TCT");
		schemaNameMap.put("TKS_INVOICE_DU","TCT");
		schemaNameMap.put("TKS_INVOICE_D3","TCT");
		schemaNameMap.put("TKS_HANTRF_CF","TCT");
		schemaNameMap.put("TKS_HANDLING_BB","TCT");
		schemaNameMap.put("TKS_HANDLING_AP","TCT");
		schemaNameMap.put("TKS_FATURA_AE","TCT");
		schemaNameMap.put("TKS_DUYURU_AK","TCT");
		schemaNameMap.put("TKS_DOM_DP","TCT");
		schemaNameMap.put("TKS_CRA_CY","TCT");
		schemaNameMap.put("TKS_CRA_AL","TCT");
		schemaNameMap.put("TKS_CODE_BA","TCT");
		schemaNameMap.put("TKS_CASS_HDR","TCT");
		schemaNameMap.put("TKS_C2K_CN","TCT");
		schemaNameMap.put("TKS_C2K_BE","TCT");
		schemaNameMap.put("TKS_BLK_H8","TCT");
		schemaNameMap.put("TKS_BLK_CH","TCT");
		schemaNameMap.put("TKS_BLK","TCT");
		schemaNameMap.put("TKS_AWB_STOCK1","TCT");
		schemaNameMap.put("TKS_AWB_GF","TCT");
		schemaNameMap.put("TKS_AWB_F2","TCT");
		schemaNameMap.put("TKS_AWB_BK","TCT");
		schemaNameMap.put("TKS_APD","TCT");
		schemaNameMap.put("TKS_AMB_OLD_F8","TCT");
		schemaNameMap.put("TKS_AMB_OLD_F3","TCT");
		schemaNameMap.put("TKS_AMB_OLD_DD","TCT");
		schemaNameMap.put("TKS_AMB_OLD_C3","TCT");
		schemaNameMap.put("TKS_AMB_OLD_BM","TCT");
		schemaNameMap.put("TKS_AMB_OLD_AA","TCT");
		schemaNameMap.put("TKS_AMB_HWB_HI","TCT");
		schemaNameMap.put("TKS_AMB_HWB_HF","TCT");
		schemaNameMap.put("TKS_AMB_HWB_GQ","TCT");
		schemaNameMap.put("TKS_AMB_HWB_GP","TCT");
		schemaNameMap.put("TKS_AMB_HWB_FA","TCT");
		schemaNameMap.put("TKS_AMB_DB20_FC","TCT");
		schemaNameMap.put("TKS_AMB_DB20_EH","TCT");
		schemaNameMap.put("TKS_AMB_DB20_EF","TCT");
		schemaNameMap.put("TKS_AMB_DB20_DB","TCT");
		schemaNameMap.put("TKS_AMB_DB20_AP","TCT");
		schemaNameMap.put("TKS_AMB_DB20_AM","TCT");
		schemaNameMap.put("TKS_AMB_DB20_AC","TCT");
		schemaNameMap.put("TFK_TKSMIS_INTERFACE_BI","TCT");
		schemaNameMap.put("TFK_TKSMIS_INTERFACE_AH","TCT");
		schemaNameMap.put("TAR_LIMUCAK_AJ","TCT");
		schemaNameMap.put("MSW_FILE2_AU","TCT");
		schemaNameMap.put("MIS_SEGMENT1_J1","TCT");
		schemaNameMap.put("MIS_SEGMENT1_FA","TCT");
		schemaNameMap.put("INSCFC1","TCT");
		schemaNameMap.put("FSS_F02_CA","TCT");
		schemaNameMap.put("FSS_F01_S6","TCT");
		schemaNameMap.put("FSS_F01_S3","TCT");
		schemaNameMap.put("FSS_F01","TCT");
		schemaNameMap.put("EKP_TARDEG_BN","TCT");
		schemaNameMap.put("UHM_NOT_AG","TCT");
		schemaNameMap.put("UHM_NOT_AE","TCT");
		schemaNameMap.put("TKS_UCT_CV","TCT");
		schemaNameMap.put("TKS_TRF_OLD_D2","TCT");
		schemaNameMap.put("TKS_TRF_OLD_D1","TCT");
		schemaNameMap.put("TKS_TRF_OLD_CY","TCT");
		schemaNameMap.put("TKS_TRF_OLD_CJ","TCT");
		schemaNameMap.put("TKS_TRF_OLD_B0","TCT");
		schemaNameMap.put("TKS_TRF_CP","TCT");
		schemaNameMap.put("TKS_TRF_CC","TCT");
		schemaNameMap.put("TKS_TRF_B0","TCT");
		schemaNameMap.put("TKS_TRF_AX","TCT");
		schemaNameMap.put("TKS_TRACE_INSURANCE_AN","TCT");
		schemaNameMap.put("TKS_TRACE_INSURANCE_AE","TCT");
		schemaNameMap.put("TKS_TRACE_INSURANCE","TCT");
		schemaNameMap.put("TKS_REZ_OLD_IND","TCT");
		schemaNameMap.put("TKS_REZ_OLD_DR","TCT");
		schemaNameMap.put("TKS_REZ_OLD_DP","TCT");
		schemaNameMap.put("TKS_REZ_OLD_DO","TCT");
		schemaNameMap.put("TKS_REZ_OLD_CM","TCT");
		schemaNameMap.put("TKS_REZ_BQ","TCT");
		schemaNameMap.put("TKS_REZ_AP","TCT");
		schemaNameMap.put("TKS_MSG_AU","TCT");
		schemaNameMap.put("TKS_MSG_A9","TCT");
		schemaNameMap.put("TKS_MSG_A3","TCT");
		schemaNameMap.put("TKS_INVOICE_BN","TCT");
		schemaNameMap.put("TKS_HANDLING_DG","TCT");
		schemaNameMap.put("TKS_GUMRUK_A7","TCT");
		schemaNameMap.put("TKS_EXC_B6","TCT");
		schemaNameMap.put("TKS_EXC_B4","TCT");
		schemaNameMap.put("TKS_EXC_B3","TCT");
		schemaNameMap.put("TKS_EXC_B0","TCT");
		schemaNameMap.put("TKS_DUYURU_AS","TCT");
		schemaNameMap.put("TKS_DOM_S2","TCT");
		schemaNameMap.put("TKS_DOM_DJ","TCT");
		schemaNameMap.put("TKS_DOM_D9","TCT");
		schemaNameMap.put("TKS_CUSTOMER_DE_BZ","TCT");
		schemaNameMap.put("TKS_CUSTOMER_DE_AO","TCT");
		schemaNameMap.put("TKS_CUSTOMER_AT","TCT");
		schemaNameMap.put("TKS_CRA_DP","TCT");
		schemaNameMap.put("TKS_CRA_DL","TCT");
		schemaNameMap.put("TKS_CRA_CX","TCT");
		schemaNameMap.put("TKS_CRA_BR","TCT");
		schemaNameMap.put("TKS_CODE_BF","TCT");
		schemaNameMap.put("TKS_CODE","TCT");
		schemaNameMap.put("TKS_CF_AM","TCT");
		schemaNameMap.put("TKS_CF","TCT");
		schemaNameMap.put("TKS_C2K_S1","TCT");
		schemaNameMap.put("TKS_BLK_JD","TCT");
		schemaNameMap.put("TKS_BLK_AF","TCT");
		schemaNameMap.put("TKS_AWB_C7","TCT");
		schemaNameMap.put("TKS_AWB_BU","TCT");
		schemaNameMap.put("TKS_AWB_B5","TCT");
		schemaNameMap.put("TKS_AWB_AP","TCT");
		schemaNameMap.put("TKS_APD_AF","TCT");
		schemaNameMap.put("TKS_AMB_OLD_EM","TCT");
		schemaNameMap.put("TKS_AMB_OLD_BW","TCT");
		schemaNameMap.put("TKS_AMB_OLD_BH","TCT");
		schemaNameMap.put("TKS_AMB_HWB_HA","TCT");
		schemaNameMap.put("TKS_AMB_HWB_GO","TCT");
		schemaNameMap.put("TKS_AMB_HWB_AY","TCT");
		schemaNameMap.put("TKS_AMB_DB20_EM","TCT");
		schemaNameMap.put("TKS_AMB_DB20_EE","TCT");
		schemaNameMap.put("TKS_AMB_DB20_D9","TCT");
		schemaNameMap.put("TKS_AMB_DB20_CJ","TCT");
		schemaNameMap.put("TKS_AMB_DB20_BW","TCT");
		schemaNameMap.put("TKS_AMB_DB20_AA","TCT");
		schemaNameMap.put("TKS_AGENCY","TCT");
		schemaNameMap.put("MIS_SEGMENT1_IG","TCT");
		schemaNameMap.put("MIS_SEGMENT1_CS","TCT");
		schemaNameMap.put("INSCFC1_DQ","TCT");
		schemaNameMap.put("INSCFC1_DI","TCT");
		schemaNameMap.put("INSCF03_BC","TCT");
		schemaNameMap.put("INSCF03_A8","TCT");
		schemaNameMap.put("FSS_F02_CG","TCT");
		schemaNameMap.put("FSS_F01_S5","TCT");
		schemaNameMap.put("FSS_F01_BH","TCT");
		schemaNameMap.put("EKP_SKTUCAK_AS","TCT");

		

	}
	

	private static boolean isTable(String isTable) {
		return schemaNameMap.containsKey(isTable);
	}

}
